/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bowjni_Bow */

#ifndef _Included_bowjni_Bow
#define _Included_bowjni_Bow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bowjni_Bow
 * Method:    train
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bowjni_Bow_train
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     bowjni_Bow
 * Method:    categoryImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bowjni_Bow_categoryImage
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     bowjni_Bow
 * Method:    categoryBySvm
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_bowjni_Bow_categoryBySvm
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
