/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bowjni_Java2cpp */

#ifndef _Included_bowjni_Java2cpp
#define _Included_bowjni_Java2cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bowjni_Java2cpp
 * Method:    train
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bowjni_Java2cpp_train
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     bowjni_Java2cpp
 * Method:    categoryImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bowjni_Java2cpp_categoryImage
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     bowjni_Java2cpp
 * Method:    categoryBySvm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bowjni_Java2cpp_categoryBySvm
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
