/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class caffejni_Caffe */

#ifndef _Included_caffejni_Caffe
#define _Included_caffejni_Caffe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     caffejni_Caffe
 * Method:    caffe
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_caffejni_Caffe_caffe
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     caffejni_Caffe
 * Method:    getType
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_caffejni_Caffe_getType
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
