/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class editjni_EditImage */

#ifndef _Included_editjni_EditImage
#define _Included_editjni_EditImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     editjni_EditImage
 * Method:    surf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_editjni_EditImage_surf
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     editjni_EditImage
 * Method:    cornerHairrs
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_editjni_EditImage_cornerHairrs
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
