/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ldajni_LdaFace */

#ifndef _Included_ldajni_LdaFace
#define _Included_ldajni_LdaFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ldajni_LdaFace
 * Method:    train
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ldajni_LdaFace_train
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ldajni_LdaFace
 * Method:    test
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ldajni_LdaFace_test
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     ldajni_LdaFace
 * Method:    predict
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ldajni_LdaFace_predict
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
